cloud:
  aws:
    credentials:
      access-key: //your access key
      secret-key: //your secret key
    region:
      static: //aws-region
    stack:
      auto: false

application:
  bucket:
    name: //bucket-name


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB


